### PR TITLE
Fix negative binomial docs

### LINKED ISSUE #46: negative binomial distribution parametrization
The `stats::*nbinom` functions are parametrized as follows (emph. mine)

>    The negative binomial distribution with size = n and ‘prob’ = p
     has density

                      Gamma(x+n)/(Gamma(n) x!) p^n (1-p)^x              
     
>    for x = 0, 1, 2, ..., n > 0 and 0 < p <= 1.

>    This represents the number of failures which occur in a sequence
     of Bernoulli trials **before a target number of successes** is
     reached.  The mean is mu = n(1-p)/p and variance n(1-p)/p^2.

In this package, it is described as:

> A generalization of the geometric distribution. It is the number of successes in a sequence of i.i.d. Bernoulli trials **before a specified number (r) of failures** occurs.

Both use `p` for the probability of **success**.

I believe in your documentation `r` is the `size` parameter (it would be great if this was made explicit in the documentation).

However looking at the source I see you are simply calling the `stats` functions which have the roles reversed.  

Now it might be very well possible I just don't get something, but it seems to me this will give "inverse" results?  The formulas for mean/variance are also different.

Edit: indeed the variance and mean formulas are equivalent if we make a `p' = 1 - p` substitution.  So something is definitely odd here.

### PR DESCRIPTION
**Pull request by mitchelloharawild**
Resolves #46

### CODE REVIEW

File: R/dist_negative_binomial.R [hunk 1]
```diff
@@ -3,8 +3,9 @@
 #' \lifecycle{stable}
 #'
 #' A generalization of the geometric distribution. It is the number
-#' of successes in a sequence of i.i.d. Bernoulli trials before
-#' a specified number (\eqn{r}) of failures occurs.
+#' of failures in a sequence of i.i.d. Bernoulli trials before
+#' a specified number of success (`size`) occurs. The probability of success in
```
Comment (Fuco1) [inline R/dist_negative_binomial.R:7]:
```suggestion
#' a specified number of successes (`size`) occurs. The probability of success in
```

**Review by Fuco1 — CHANGES_REQUESTED** [review]
Just a typo

File: R/dist_negative_binomial.R (hunk 1 above)
Comment (Fuco1) [reply R/dist_negative_binomial.R:7]: I'm not sure about the verb actually... if it goes with "number" or "successes".  But the original had "failures" so I'd go with plural.
